services:
  db:
      image: mysql
      container_name: db
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: 'doggroomer'
        MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_BackAppDogGroomer
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"

  BackAppDogGroomer:    
    image: davidevcueto/backappdoggroomer:latest
    container_name: backappdoggroomer

    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/doggroomer
      - server.port=8080
    
    ports:
      - '8080:8080'
      
    depends_on:
      - db
